ALTER TYPE "movement_type" ADD VALUE IF NOT EXISTS 'TRANSFER_OUT';
ALTER TYPE "movement_type" ADD VALUE IF NOT EXISTS 'TRANSFER_IN';
ALTER TYPE "movement_type" ADD VALUE IF NOT EXISTS 'COUNT_IN';
ALTER TYPE "movement_type" ADD VALUE IF NOT EXISTS 'COUNT_OUT';
